# base image  
FROM python:3.10.8   
# setup environment variable  
ENV DockerHOME=/home/app/webapp  

# set work directory  
RUN mkdir -p $DockerHOME  

# where your code lives  
WORKDIR $DockerHOME

# upgrade pip 
RUN pip install --upgrade pip

# copy whole project to your docker home directory. 
COPY . $DockerHOME  

# install dependencies
RUN pip install -r requirements.txt

# port where the Django app runs  
EXPOSE 8000  

# ADD entrypoint.sh /entrypoint.sh
# RUN chmod a+x /entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]

CMD python manage.py migrate && gunicorn bitespeed_identity_reconciliation.wsgi:application --bind 0.0.0.0:8000