# Generated by Django 4.2.2 on 2023-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linkPrecedence',
            field=models.CharField(choices=[('secondary', 'Secondary'), ('primary', 'Primary')], default='primary', max_length=10),
        ),
    ]
